name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        PROXY_URL: ${{ secrets.PROXY_URL }}
        ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}
      run: |
        echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> .env
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
        echo "OPENAI_API_BASE=$OPENAI_API_BASE" >> .env
        echo "PROXY_URL=$PROXY_URL" >> .env
        echo "ALLOWED_USERS=$ALLOWED_USERS" >> .env
    
    - name: Deploy to server
      if: ${{ env.SERVER_HOST != '' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ env.SERVER_SSH_KEY }}
        script: |
          cd ~/gpt-telegram-bot
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl restart gpt-telegram-bot 